export const shortLetFeatures = {
  General_Features: [
    "hasEnsuite",
    "hasPoPCeiling",
    "hasWalkInClosets",
    "hasAirConditioning",
    "hasSpeedInternet",
    "hasWineCeller",
    "hasWashingMachine",
    "hasDryer",
    "hasFurnished",
    "hasWifi",
    "hasHighSpeedInternet",
    "hasPresingIron",
    "hasFibreOptics",
    "hasSatelliteTV",
    "hasTelevision",
    "hasElevator",
    "hasBoysQuarters",
    "hasSmartHomeTechnology",
    "hasUpgradedBathroomFeatures",
    "hasSpaLikeFeatures",
    "hasTileOrMarbleFeatures",
  ],
  Entertainment_Features: [
    "hasFoosball",
    "hasPoolOrSnookerTable",
    "hasBoardGames",
    "hasPS5",
    "hasXbox",
    "hasNetflix",
    "hasAmazonPrime",
    "hasShowMax",
    "hasTableTennis",
    "hasHomeTheater",
  ],
  Kitchen_Features: [
    "hasFullyEquippedKitcken",
    "hasModernAppliances",
    "hasGraniteCountertops",
    "hasRefrigerator",
    "hasBreakfastBar",
    "HasStorageRoom",
    "hasKettle",
    "hasCookingGas",
    "hasMicrowave",
    "hasOven",
  ],
  Bathroom_Features: [
    "hasBathtub",
    "hasStandingShower",
    "hasHeaterAndHotWater",
    "hasMarbleWalls",
  ],
  Living_Room_Features: [
    "hasOpenFloorPlan",
    "hasLargeWindwos",
    "hasBuiltInHouseTheater",
  ],
  Outdoor_Features: [
    "hasPrivateBackyard",
    "hasPatioOrDarkSpace",
    "hasLandscapedGarden",
    "hasSwimmingPool",
  ],
  Home_Office_Features: [
    "hasHomeOfficeSpace",
    "hasBuiltInShelfOrBookSpace",
    "hasAmpleNaturalLight",
  ],
  Safety_and_Security_Features: [
    "hasSecuritySystem",
    "hasBulletProofDoors",
    "hasGatedCompound",
    "hasReinforcedDoorsAndWindows",
    "hasGaurdedCommunity",
    "hasUniformedSecurity",
    "hasArmedGuards",
  ],
  Parking_Features: [
    "hasParkingGarage",
    "hasDriveWaySpace",
    "hasStreetParkingAvaliability",
    "hasPrivateParkingSpace",
  ],
  Utilities_Features: [
    "hasElectricity",
    "hasBackupGenerator",
    "hasInverter",
    "hasBorehole",
    "hasWaterBoard",
  ],
  Community_Features: [
    "hasProximityToSchools",
    "hasProximityToShoppingMalls",
    "hasProximityToSupermarkets",
    "hasNearByPublicTransportation",
    "hasAccessiblityViaBoltOrUber",
  ],
  Pet_Features: [
    "hasFencedBackyard",
    "hasPetFriendlyNeighbourhood",
    "hasNearbyWalkingTrailsAndSidewalks",
  ],
};
