export type User = {
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  gender: string | null;
  phoneNumber: string;
  address: string | null;
  organizationId: string;
  organization: Organization;
  verificationCode: string;
  roleId: string;
  applicationRole: Role;
  profilePicture: string | null;
  withInNigeria: boolean;
  age: number;
  income: number;
  preferredPurchaseOption: string | null;
  partnerIncome: number;
  partnerAge: number;
  partnerEmail: string | null;
  maritalStatus: string | null;
  howDidYouHearOfUs: string | null;
  city: string | null;
  isAViewingAgent: boolean;
  isContactStaff: boolean;
  countryId: string | null;
  country: string | null;
  stateId: string | null;
  state: string | null;
  lastLoginDate: string;
  dateOfBirth: string | null;
  isActive: boolean;
  isDeleted: boolean;
  affordability: string | null;
  verifications: Array<string | null>;
  accounts: Array<string | null>;
  bio: string | null;
  designation: string | null;
  title: string | null;
  id: string;
  createdBy: string;
  dateCreated: string;
  dateLastModified: string | null;
  lastModifiedBy: string | null;
};

export type Organization = {
  name: string;
  address: string;
  description: string | null;
  emailAddress: string;
  phoneNumber: string;
  mobileNumber: string | null;
  logo: string | null;
  coverImage: string | null;
  brandColorCode: string | null;
  bankName: string | null;
  accountNumber: string | null;
  bankCode: string | null;
  longitude: number;
  latitude: number;
  yearsInOperation: number;
  city: string | null;
  interview: string | null;
  documents: string | null;
  organizationType: string | null;
  estates: Array<string | null>;
  propertyCount: string | null;
  partnerships: string | null;
  houses: Array<string | null>;
  verifications: Array<string | null>;
  id: string;
  createdBy: string;
  dateCreated: string;
  dateLastModified: string | null;
  lastModifiedBy: string | null;
};

export type Role = {
  id: string;
  name: string;
  access: string;
  description: string;
  identifier: string | null;
  createdBy: string;
  dateCreated: string;
  lastModifiedBy: string | null;
  dateLastModified: string;
};
