import type { Metadata } from "next";
import localFont from "next/font/local";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import { AuthenticationProvider } from "@/context/AuthContext";
import { getSession } from "@/server-actions/get-session";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const millik = localFont({
  src: "./fonts/Millik.otf",
  variable: "--font-millik",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { token, isLoggedIn } = await getSession();

  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.variable} ${millik.variable}  font-sans antialiased bg-primary-gradient`}>
        <Providers>
          <AuthenticationProvider value={{ token }}>
            {children}
          </AuthenticationProvider>
        </Providers>
      </body>
    </html>
  );
}
