// account
export const REGISTER_USER_KEY = "REGISTER USER";
export const LOGIN_USER_KEY = "LOGIN USER";
export const LOGIN_GOOGLE_USER_KEY = "LOGIN GOOGLE USER";
export const FORGOT_PASSWORD_KEY = "FORGOT PASSWORD";
export const RESET_PASSWORD_KEY = "RESET PASSWORD";
export const VERIFY_EMAIL_KEY = "VERIFY EMAIL";

// short-lets
export const GET_ALL_SHORT_LETS_KEY = "GET ALL SHORT LETS";
export const GET_SHORT_LETS_IN_A_CITY_KEY = "GET SHORT LETS IN A CITY";
export const RESERVE_SHORT_LET_KEY = "RESERVE SHORT LET";
export const GET_CONTACT_AGENTS_FOR_SHORTLET_KEY =
  "GET ORGANIZATION CONTACT STAFF";

// news letter
export const JOIN_NEWSLETTER_KEY = "JOIN NEWSLETTER KEY";

// locations
export const GET_CITIES_IN_A_STATE_KEY = "GET CITIES IN A STATE";

// google maps
export const GET_COORDINATES_KEY = "GET COORDINATES";

// exchange rate
export const GET_EXCHANGE_RATES_KEY = "GET EXCHANGES RATE";
