// account
export const REGISTER_USER_KEY = "REGISTER USER";
export const LOGIN_USER_KEY = "LOGIN USER";
export const LOGIN_GOOGLE_USER_KEY = "LOGIN GOOGLE USER";
export const FORGOT_PASSWORD_KEY = "FORGOT PASSWORD";
export const RESET_PASSWORD_KEY = "RESET PASSWORD";
export const VERIFY_EMAIL_KEY = "VERIFY EMAIL";

// short-lets
export const GET_ALL_SHORT_LETS_KEY = "GET ALL SHORT LETS";
